In [1]:
import dash
import dash_core_components as dcc
import dash_html_components as html
#import dash_bootstrap_components as dbc
from dash.dependencies import Output, Input
from dash_table import DataTable
import plotly.express as px
import pandas as pd
import numpy as np
from bubbly.bubbly import bubbleplot

In [2]:
data = pd.read_csv("owid-covid-data.csv")
print(data.dtypes)
print(data.columns)

Unnamed: 0                              int64
iso_code                               object
continent                              object
location                               object
date                                   object
total_cases                           float64
new_cases                             float64
new_cases_smoothed                    float64
total_deaths                          float64
new_deaths                            float64
new_deaths_smoothed                   float64
total_cases_per_million               float64
new_cases_per_million                 float64
new_cases_smoothed_per_million        float64
total_deaths_per_million              float64
new_deaths_per_million                float64
new_deaths_smoothed_per_million       float64
reproduction_rate                     float64
icu_patients                          float64
icu_patients_per_million              float64
hosp_patients                         float64
hosp_patients_per_million             float64
weekly_icu_admissions                 float64
weekly_icu_admissions_per_million     float64
weekly_hosp_admissions                float64
weekly_hosp_admissions_per_million    float64
total_tests                           float64
new_tests                             float64
total_tests_per_thousand              float64
new_tests_per_thousand                float64
new_tests_smoothed                    float64
new_tests_smoothed_per_thousand       float64
tests_per_case                        float64
positive_rate                         float64
tests_units                            object
stringency_index                      float64
population                            float64
population_density                    float64
median_age                            float64
aged_65_older                         float64
aged_70_older                         float64
gdp_per_capita                        float64
extreme_poverty                       float64
cardiovasc_death_rate                 float64
diabetes_prevalence                   float64
female_smokers                        float64
male_smokers                          float64
handwashing_facilities                float64
hospital_beds_per_thousand            float64
life_expectancy                       float64
human_development_index               float64
lat                                   float64
long                                  float64
dtype: object
Index(['Unnamed: 0', 'iso_code', 'continent', 'location', 'date',
       'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths',
       'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'lat', 'long'],
      dtype='object')

In [25]:
data["date"] = pd.to_datetime(data["date"])
data = data.sort_values(by = "date")
data["total_cases_diff"] = data["total_cases"].diff()

In [4]:
#df = data.transpose()
#df.columns = df.iloc[1]
#df = df.reset_index()
#df = df.drop([0,1,2,3])
#df = df.reset_index(drop = True)
data = data.fillna(0)
data["continent"] = data["continent"].astype('category')
#data["weekly_hosp_admissions"] = data["weekly_hosp_admissions"].astype('int')

In [26]:
df = data.groupby(['date','location']).sum().fillna(0)
df.head()

                        Unnamed: 0  total_cases  new_cases  \
date       location
2019-12-31 Afghanistan         251          0.0        0.0
           Algeria           15158          0.0        0.0
           Armenia            2183          0.0        0.0
           Australia          2761          0.0        0.0
           Austria            3090          0.0        0.0

                        new_cases_smoothed  total_deaths  new_deaths  \
date       location
2019-12-31 Afghanistan                 0.0           0.0         0.0
           Algeria                     0.0           0.0         0.0
           Armenia                     0.0           0.0         0.0
           Australia                   0.0           0.0         0.0
           Austria                     0.0           0.0         0.0

                        new_deaths_smoothed  total_cases_per_million  \
date       location
2019-12-31 Afghanistan                  0.0                      0.0
           Algeria                      0.0                      0.0
           Armenia                      0.0                      0.0
           Australia                    0.0                      0.0
           Austria                      0.0                      0.0

                        new_cases_per_million  new_cases_smoothed_per_million  \
date       location
2019-12-31 Afghanistan                    0.0                             0.0
           Algeria                        0.0                             0.0
           Armenia                        0.0                             0.0
           Australia                      0.0                             0.0
           Austria                        0.0                             0.0

                        ...  female_smokers  male_smokers  \
date       location     ...
2019-12-31 Afghanistan  ...             0.0           0.0
           Algeria      ...             0.7          30.4
           Armenia      ...             1.5          52.1
           Australia    ...            13.0          16.5
           Austria      ...            28.4          30.9

                        handwashing_facilities  hospital_beds_per_thousand  \
date       location
2019-12-31 Afghanistan                  37.746                        0.50
           Algeria                      83.741                        1.90
           Armenia                      94.043                        4.20
           Australia                     0.000                        3.84
           Austria                       0.000                        7.37

                        life_expectancy  human_development_index        lat  \
date       location
2019-12-31 Afghanistan            64.83                    0.498  33.939110
           Algeria                76.88                    0.754  28.033886
           Armenia                75.09                    0.755  40.069099
           Australia              83.44                    0.939 -25.274398
           Austria                81.54                    0.908  47.516231

                              long  total_cases_diff     timestamp
date       location
2019-12-31 Afghanistan   67.709953               0.0  1.577750e+09
           Algeria        1.659626               0.0  1.577750e+09
           Armenia       45.038189               0.0  1.577750e+09
           Australia    133.775136               0.0  1.577750e+09
           Austria       14.550072               0.0  1.577750e+09

[5 rows x 50 columns]

In [27]:
from __future__ import division
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode()
from bubbly.bubbly import bubbleplot
#ata["timestamp"] = data["date"].astype(int) / 10**9

figure = bubbleplot(dataset=df
                    x_column='date',
                    y_column='weekly_hosp_admissions',
                    bubble_column = 'location',
                    size_column = 'total_cases',
                    #ime_column = 'timestamp',
                    x_title="something",
                    y_title="something else",
                    title='GØJL', 
                    height=650)

iplot(figure, config={'scrollzoom': True})

SyntaxError: invalid syntax (<ipython-input-27-56f251a49b96>, line 8)

In [19]:
data["timestamp"] = data["timestamp"].astype(int)/10**9
data["timestamp"]

5581     1.57775
45235    1.57775
10007    1.57775
2183     1.57775
3090     1.57775
          ...
10848    1.60609
44326    1.60609
10590    1.60609
43530    1.60609
58697    1.60609
Name: timestamp, Length: 58698, dtype: float64

In [21]:

figure = bubbleplot(dataset=data,
                    x_column='date',
                    y_column='weekly_hosp_admissions',
                    bubble_column = 'location',
                    size_column = 'total_cases',
                    #time_column = 'timestamp',
                    x_title="something",
                    y_title="something else",
                    title='GØJL', 
                    height=650)

iplot(figure, config={'scrollzoom': True})

TypeError: unsupported operand type(s) for *: 'Timestamp' and 'float'